
CREATE TABLE PLAN_NODE (
    NODE_ID UUID NOT null primary key,
    ROOT_NODE UUID not null ,
    PARENT_NODE UUID NULL,
    NODE_POSITION INTEGER,
    TYPE INTEGER NOT NULL,
    NAME VARCHAR(500) NOT NULL,
    IDENTIFIER VARCHAR(100),
    LANGUAGE VARCHAR(10),
    SOURCE VARCHAR(500),
    KEYWORD VARCHAR(100),
    DESCRIPTION TEXT,
    DISPLAY VARCHAR(100),
    DATA_TABLE TEXT,
    DOCUMENT TEXT,
    DOCUMENT_MIME_TYPE VARCHAR(100)
);

ALTER TABLE PLAN_NODE ADD CONSTRAINT fk_plan_node_parent FOREIGN KEY (PARENT_NODE) REFERENCES PLAN_NODE (NODE_ID) on delete CASCADE;
ALTER TABLE PLAN_NODE ADD CONSTRAINT fk_plan_node_root FOREIGN KEY (ROOT_NODE) REFERENCES PLAN_NODE (NODE_ID) ON DELETE CASCADE;

CREATE INDEX idx_plan_node_parent ON plan_node(parent_node);
CREATE INDEX idx_plan_node_root ON plan_node(root_node);
CREATE INDEX idx_plan_node_root_parent ON plan_node(root_node, parent_node);


CREATE TABLE PLAN_NODE_TAG (
    PLAN_NODE UUID,
    TAG VARCHAR(50) NOT NULL
);
ALTER TABLE PLAN_NODE_TAG ADD CONSTRAINT pk_plan_node_tag PRIMARY KEY (PLAN_NODE, TAG);
ALTER TABLE PLAN_NODE_TAG ADD CONSTRAINT fk_plan_node_tag_node FOREIGN KEY (PLAN_NODE) REFERENCES PLAN_NODE (NODE_ID) ON DELETE CASCADE;

CREATE TABLE PLAN_NODE_PROPERTY (
    PLAN_NODE UUID,
    KEY VARCHAR(50) NOT NULL,
    VALUE VARCHAR(100)
);
ALTER TABLE PLAN_NODE_PROPERTY ADD CONSTRAINT pk_plan_node_property PRIMARY KEY (PLAN_NODE, KEY);
ALTER TABLE PLAN_NODE_PROPERTY ADD CONSTRAINT fk_plan_node_property_node FOREIGN KEY (PLAN_NODE) REFERENCES PLAN_NODE (NODE_ID) ON DELETE CASCADE;

