
CREATE TABLE PLAN_NODE (
    NODE_ID UUID NOT NULL PRIMARY KEY,
    ROOT_NODE UUID NOT NULL,
    PARENT_NODE UUID NULL,
    NODE_POSITION INTEGER,
    TYPE INTEGER NOT NULL,
    NAME VARCHAR(500) NOT NULL,
    IDENTIFIER VARCHAR(100),
    LANGUAGE VARCHAR(10),
    SOURCE VARCHAR(500),
    KEYWORD VARCHAR(100),
    DESCRIPTION LONGVARCHAR,
    DISPLAY VARCHAR(100),
    DATA_TABLE LONGVARCHAR,
    DOCUMENT LONGVARCHAR,
    DOCUMENT_MIME_TYPE VARCHAR(100)
);

ALTER TABLE PLAN_NODE ADD CONSTRAINT fk_plan_node_parent FOREIGN KEY (PARENT_NODE) REFERENCES PLAN_NODE (NODE_ID) ON DELETE CASCADE;
ALTER TABLE PLAN_NODE ADD CONSTRAINT fk_plan_node_root FOREIGN KEY (ROOT_NODE) REFERENCES PLAN_NODE (NODE_ID) ON DELETE CASCADE;

CREATE INDEX idx_plan_node_parent ON PLAN_NODE(PARENT_NODE);
CREATE INDEX idx_plan_node_root ON PLAN_NODE(ROOT_NODE);
CREATE INDEX idx_plan_node_root_parent ON PLAN_NODE(ROOT_NODE, PARENT_NODE);


CREATE TABLE PLAN_NODE_TAG (
    PLAN_NODE UUID,
    TAG VARCHAR(50) NOT NULL,
    CONSTRAINT pk_plan_node_tag PRIMARY KEY (PLAN_NODE, TAG),
    CONSTRAINT fk_plan_node_tag_node FOREIGN KEY (PLAN_NODE) REFERENCES PLAN_NODE (NODE_ID) ON DELETE CASCADE
);

CREATE TABLE PLAN_NODE_PROPERTY (
    PLAN_NODE UUID,
    KEY VARCHAR(50) NOT NULL,
    VALUE VARCHAR(100),
    CONSTRAINT pk_plan_node_property PRIMARY KEY (PLAN_NODE, KEY),
    CONSTRAINT fk_plan_node_property_node FOREIGN KEY (PLAN_NODE) REFERENCES PLAN_NODE (NODE_ID) ON DELETE CASCADE
);