#!/bin/sh
set -e

# Resolve script path following symlinks
PRG="$0"
while [ -h "$PRG" ]; do
    PRG="$(readlink "$PRG")"
done
BIN_DIR="$(cd "$(dirname "$PRG")" && pwd)"
APP_HOME="$(dirname "$BIN_DIR")"

exec java \
  --module-path "$APP_HOME/lib" \
  --add-modules ALL-MODULE-PATH \
  --module org.myjtools.openbbt.core.cli/org.myjtools.openbbt.core.cli.MainCommand \
  "$@"