
CREATE TABLE PLAN_NODE (
    NODE_ID UUID NOT NULL PRIMARY KEY,
    PARENT_NODE UUID NULL,
    NODE_POSITION INTEGER,
    TYPE INTEGER NOT NULL,
    NAME VARCHAR(500) NULL,
    IDENTIFIER VARCHAR(100),
    LANGUAGE VARCHAR(10),
    SOURCE VARCHAR(500),
    KEYWORD VARCHAR(100),
    DESCRIPTION TEXT,
    DISPLAY VARCHAR(100),
    DATA_TABLE TEXT,
    DOCUMENT TEXT,
    DOCUMENT_MIME_TYPE VARCHAR(100),
    PLAN_ID UUID NULL,
    VALIDATION_STATUS  INTEGER NULL,
    VALIDATION_MESSAGE VARCHAR(500) NULL,
    HAS_ISSUES         BOOLEAN DEFAULT FALSE NOT NULL,
    TEST_CASE_COUNT    INTEGER NULL
);

ALTER TABLE PLAN_NODE ADD CONSTRAINT fk_plan_node_parent FOREIGN KEY (PARENT_NODE) REFERENCES PLAN_NODE (NODE_ID) ON DELETE CASCADE;

CREATE INDEX idx_plan_node_parent ON PLAN_NODE(PARENT_NODE);


CREATE TABLE PLAN_NODE_TAG (
    PLAN_NODE UUID,
    TAG VARCHAR(50) NOT NULL
);
ALTER TABLE PLAN_NODE_TAG ADD CONSTRAINT pk_plan_node_tag PRIMARY KEY (PLAN_NODE, TAG);
ALTER TABLE PLAN_NODE_TAG ADD CONSTRAINT fk_plan_node_tag_node FOREIGN KEY (PLAN_NODE) REFERENCES PLAN_NODE (NODE_ID) ON DELETE CASCADE;

CREATE TABLE PLAN_NODE_PROPERTY (
    PLAN_NODE UUID,
    KEY VARCHAR(50) NOT NULL,
    VALUE VARCHAR(100)
);
ALTER TABLE PLAN_NODE_PROPERTY ADD CONSTRAINT pk_plan_node_property PRIMARY KEY (PLAN_NODE, KEY);
ALTER TABLE PLAN_NODE_PROPERTY ADD CONSTRAINT fk_plan_node_property_node FOREIGN KEY (PLAN_NODE) REFERENCES PLAN_NODE (NODE_ID) ON DELETE CASCADE;


CREATE TABLE PROJECT (
    PROJECT_ID UUID NOT NULL,
    ORGANIZATION_NAME VARCHAR(200) NOT NULL,
    PROJECT_NAME VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT NULL,
    CONSTRAINT PROJECT_PK PRIMARY KEY (PROJECT_ID),
    CONSTRAINT PROJECT_NAME_UK UNIQUE (ORGANIZATION_NAME, PROJECT_NAME)
);

CREATE TABLE PLAN (
    PLAN_ID UUID NOT NULL,
    PROJECT_ID UUID NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    RESOURCE_SET_HASH VARCHAR(100) NOT NULL,
    CONFIGURATION_HASH VARCHAR(200) NOT NULL,
    PLAN_NODE_ROOT UUID NOT NULL,
    TEST_CASE_COUNT INTEGER NULL,
    PROFILE VARCHAR(200) NULL,
    CONSTRAINT PLAN_PK PRIMARY KEY (PLAN_ID),
    CONSTRAINT PLAN_PLAN_NODE_FK FOREIGN KEY (PLAN_NODE_ROOT) REFERENCES PLAN_NODE(NODE_ID) ON DELETE CASCADE,
    CONSTRAINT PLAN_PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE PLAN_NODE ADD CONSTRAINT PLAN_NODE_PLAN_FK FOREIGN KEY (PLAN_ID) REFERENCES PLAN(PLAN_ID) ON DELETE SET NULL;


CREATE TABLE EXECUTION (
    EXECUTION_ID UUID NOT NULL,
    PLAN_ID UUID NOT NULL,
    EXECUTED_AT TIMESTAMP NOT NULL,
    TEST_PASSED_COUNT INTEGER NULL,
    TEST_ERROR_COUNT INTEGER NULL,
    TEST_FAILED_COUNT INTEGER NULL,
    CONSTRAINT EXECUTION_PK PRIMARY KEY (EXECUTION_ID),
    CONSTRAINT EXECUTION_PLAN_FK FOREIGN KEY (PLAN_ID) REFERENCES PLAN(PLAN_ID) ON DELETE CASCADE
);

CREATE TABLE EXECUTION_NODE (
    EXECUTION_NODE_ID UUID NOT NULL,
    EXECUTION_ID UUID NOT NULL,
    PLAN_NODE_ID UUID NOT NULL,
    STARTED_AT TIMESTAMP NULL,
    FINISHED_AT TIMESTAMP NULL,
    RESULT INTEGER NULL,
    MESSAGE TEXT NULL,
    TEST_PASSED_COUNT INTEGER NULL,
    TEST_ERROR_COUNT INTEGER NULL,
    TEST_FAILED_COUNT INTEGER NULL,
    CONSTRAINT EXECUTION_NODE_PK PRIMARY KEY (EXECUTION_NODE_ID),
    CONSTRAINT EXECUTION_NODE_EXECUTION_FK FOREIGN KEY (EXECUTION_ID) REFERENCES EXECUTION(EXECUTION_ID) ON DELETE CASCADE,
    CONSTRAINT EXECUTION_NODE_PLAN_NODE_FK FOREIGN KEY (PLAN_NODE_ID) REFERENCES PLAN_NODE(NODE_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_EXECUTION_NODE_LOOKUP ON EXECUTION_NODE(EXECUTION_ID, PLAN_NODE_ID);

CREATE TABLE EXECUTION_ATTACHMENT (
    ATTACHMENT_ID UUID NOT NULL,
    EXECUTION_NODE_ID UUID NOT NULL,
    EXECUTION_ID UUID NOT NULL,
    CONSTRAINT EXECUTION_ATTACHMENT_PK PRIMARY KEY (ATTACHMENT_ID),
    CONSTRAINT EXECUTION_ATTACHMENT_NODE_FK FOREIGN KEY (EXECUTION_NODE_ID) REFERENCES EXECUTION_NODE(EXECUTION_NODE_ID) ON DELETE CASCADE,
    CONSTRAINT EXECUTION_ATTACHMENT_EXECUTION_FK FOREIGN KEY (EXECUTION_ID) REFERENCES EXECUTION(EXECUTION_ID) ON DELETE CASCADE
);
