
CREATE TABLE PLAN_NODE (
    NODE_ID UUID NOT NULL PRIMARY KEY,
    PARENT_NODE UUID NULL,
    NODE_POSITION INTEGER,
    TYPE INTEGER NOT NULL,
    NAME VARCHAR(500) NULL,
    IDENTIFIER VARCHAR(100),
    LANGUAGE VARCHAR(10),
    SOURCE VARCHAR(500),
    KEYWORD VARCHAR(100),
    DESCRIPTION TEXT,
    DISPLAY VARCHAR(100),
    DATA_TABLE TEXT,
    DOCUMENT TEXT,
    DOCUMENT_MIME_TYPE VARCHAR(100),
    PLAN_ID UUID NULL,
    VALIDATION_STATUS  INTEGER NULL,
    VALIDATION_MESSAGE VARCHAR(500) NULL,
    HAS_ISSUES         BOOLEAN DEFAULT FALSE NOT NULL
);

ALTER TABLE PLAN_NODE ADD CONSTRAINT fk_plan_node_parent FOREIGN KEY (PARENT_NODE) REFERENCES PLAN_NODE (NODE_ID) ON DELETE CASCADE;

CREATE INDEX idx_plan_node_parent ON PLAN_NODE(PARENT_NODE);


CREATE TABLE PLAN_NODE_TAG (
    PLAN_NODE UUID,
    TAG VARCHAR(50) NOT NULL
);
ALTER TABLE PLAN_NODE_TAG ADD CONSTRAINT pk_plan_node_tag PRIMARY KEY (PLAN_NODE, TAG);
ALTER TABLE PLAN_NODE_TAG ADD CONSTRAINT fk_plan_node_tag_node FOREIGN KEY (PLAN_NODE) REFERENCES PLAN_NODE (NODE_ID) ON DELETE CASCADE;

CREATE TABLE PLAN_NODE_PROPERTY (
    PLAN_NODE UUID,
    KEY VARCHAR(50) NOT NULL,
    VALUE VARCHAR(100)
);
ALTER TABLE PLAN_NODE_PROPERTY ADD CONSTRAINT pk_plan_node_property PRIMARY KEY (PLAN_NODE, KEY);
ALTER TABLE PLAN_NODE_PROPERTY ADD CONSTRAINT fk_plan_node_property_node FOREIGN KEY (PLAN_NODE) REFERENCES PLAN_NODE (NODE_ID) ON DELETE CASCADE;


CREATE TABLE PROJECT (
    PROJECT_ID UUID NOT NULL,
    ORGANIZATION_NAME VARCHAR(200) NOT NULL,
    PROJECT_NAME VARCHAR(200) NOT NULL,
    CONSTRAINT PROJECT_PK PRIMARY KEY (PROJECT_ID),
    CONSTRAINT PROJECT_NAME_UK UNIQUE (ORGANIZATION_NAME, PROJECT_NAME)
);

CREATE TABLE PLAN (
    PLAN_ID UUID NOT NULL,
    PROJECT_ID UUID NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    RESOURCE_SET_HASH VARCHAR(100) NOT NULL,
    CONFIGURATION_HASH VARCHAR(200) NOT NULL,
    PLAN_NODE_ROOT UUID NOT NULL,
    CONSTRAINT PLAN_PK PRIMARY KEY (PLAN_ID),
    CONSTRAINT PLAN_PLAN_NODE_FK FOREIGN KEY (PLAN_NODE_ROOT) REFERENCES PLAN_NODE(NODE_ID) ON DELETE CASCADE,
    CONSTRAINT PLAN_PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE PLAN_NODE ADD CONSTRAINT PLAN_NODE_PLAN_FK FOREIGN KEY (PLAN_ID) REFERENCES PLAN(PLAN_ID) ON DELETE SET NULL;
