
CREATE TABLE PLAN_NODE (
    NODE_ID UUID NOT null primary key,
    PARENT_NODE UUID NULL,
    NODE_POSITION INTEGER,
    TYPE INTEGER NOT NULL,
    NAME VARCHAR(500) NULL,
    IDENTIFIER VARCHAR(100),
    LANGUAGE VARCHAR(10),
    SOURCE VARCHAR(500),
    KEYWORD VARCHAR(100),
    DESCRIPTION TEXT,
    DISPLAY VARCHAR(100),
    DATA_TABLE TEXT,
    DOCUMENT TEXT,
    DOCUMENT_MIME_TYPE VARCHAR(100)
);

ALTER TABLE PLAN_NODE ADD CONSTRAINT fk_plan_node_parent FOREIGN KEY (PARENT_NODE) REFERENCES PLAN_NODE (NODE_ID) on delete CASCADE;

CREATE INDEX idx_plan_node_parent ON plan_node(parent_node);


CREATE TABLE PLAN_NODE_TAG (
    PLAN_NODE UUID,
    TAG VARCHAR(50) NOT NULL
);
ALTER TABLE PLAN_NODE_TAG ADD CONSTRAINT pk_plan_node_tag PRIMARY KEY (PLAN_NODE, TAG);
ALTER TABLE PLAN_NODE_TAG ADD CONSTRAINT fk_plan_node_tag_node FOREIGN KEY (PLAN_NODE) REFERENCES PLAN_NODE (NODE_ID) ON DELETE CASCADE;

CREATE TABLE PLAN_NODE_PROPERTY (
    PLAN_NODE UUID,
    KEY VARCHAR(50) NOT NULL,
    VALUE VARCHAR(100)
);
ALTER TABLE PLAN_NODE_PROPERTY ADD CONSTRAINT pk_plan_node_property PRIMARY KEY (PLAN_NODE, KEY);
ALTER TABLE PLAN_NODE_PROPERTY ADD CONSTRAINT fk_plan_node_property_node FOREIGN KEY (PLAN_NODE) REFERENCES PLAN_NODE (NODE_ID) ON DELETE CASCADE;


CREATE TABLE EXECUTION_NODE (
    PLAN_NODE UUID NOT NULL,
    EXECUTION_ID UUID NOT NULL,
    RESULT SMALLINT NULL,
    STATUS SMALLINT NOT NULL,
    MESSAGE VARCHAR(200) NULL,
    STARTED TIMESTAMP NULL,
    FINISHED TIMESTAMP NULL,
    ELAPSED_TIME_MS BIGINT NULL,
    NUM_PASSED INTEGER DEFAULT 0 NOT NULL,
    NUM_FAILED INTEGER DEFAULT 0 NOT NULL,
    NUM_ERROR INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT execution_node_pk PRIMARY KEY (PLAN_NODE, EXECUTION_ID),
    CONSTRAINT execution_node_plan_node_fk FOREIGN KEY (PLAN_NODE) REFERENCES PLAN_NODE(NODE_ID) ON DELETE CASCADE
);


CREATE TABLE ORGANIZATION (
    NAME VARCHAR(100) NOT NULL,
    CONSTRAINT organization_pk PRIMARY KEY (NAME)
);


CREATE TABLE PROJECT (
    ORGANIZATION_NAME VARCHAR(200) NULL,
    PROJECT_NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(200) NULL,
    CONSTRAINT project_pk PRIMARY KEY (ORGANIZATION_NAME, PROJECT_NAME),
    CONSTRAINT project_organization_fk FOREIGN KEY (ORGANIZATION_NAME) REFERENCES ORGANIZATION(NAME) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE PLAN (
    PROJECT_NAME VARCHAR(200) NOT NULL,
    PLAN_ID UUID NOT NULL,
    ORGANIZATION_NAME VARCHAR(200) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    RESOURCE_SET_HASH VARCHAR(100) NOT NULL,
    CONFIGURATION_HASH VARCHAR(200) NOT NULL,
    PLAN_NODE_ROOT UUID NOT NULL,
    CONSTRAINT plan_pk PRIMARY KEY (PLAN_ID),
    CONSTRAINT plan_plan_node_fk FOREIGN KEY (PLAN_NODE_ROOT) REFERENCES PLAN_NODE(NODE_ID) ON DELETE CASCADE,
    CONSTRAINT plan_project_fk FOREIGN KEY (ORGANIZATION_NAME, PROJECT_NAME) REFERENCES PROJECT(ORGANIZATION_NAME, PROJECT_NAME) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE SUITE (
    PLAN_ID UUID NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    TAG_EXPRESSION VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(200) NULL,
    CONSTRAINT suite_pk PRIMARY KEY (PLAN_ID, NAME),
    CONSTRAINT suite_plan_fk FOREIGN KEY (PLAN_ID) REFERENCES PLAN(PLAN_ID) ON DELETE CASCADE
);
