package org.myjtools.openbbt.docgen;

import org.junit.jupiter.api.Test;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

class ConfigDocMarkdownGeneratorTest {

    private final ConfigDocMarkdownGenerator generator = new ConfigDocMarkdownGenerator();

    private ConfigDocEntry minimalEntry(String type) {
        return new ConfigDocEntry(null, type, false, null, null, null, null, null);
    }

    @Test
    void generate_includesTitleAsH1() {
        var result = generator.generate("Config Docs", "config.yaml", Map.of());
        assertThat(result).startsWith("# Config Docs\n");
    }

    @Test
    void generate_includesAutogeneratedNotice() {
        var result = generator.generate("Title", "config.yaml", Map.of());
        assertThat(result).contains("> Autogenerated from `config.yaml`. Do not edit manually.");
    }

    @Test
    void generate_includesKeyAsH3() {
        var result = generator.generate("Title", "f.yaml", Map.of("my.prop", minimalEntry("text")));
        assertThat(result).contains("### `my.prop`");
    }

    @Test
    void generate_includesDescription() {
        var entry = new ConfigDocEntry("A useful property.", "text", false, null, null, null, null, null);
        var result = generator.generate("Title", "f.yaml", Map.of("p", entry));
        assertThat(result).contains("A useful property.");
    }

    @Test
    void generate_skipsDescriptionWhenNull() {
        var result = generator.generate("Title", "f.yaml", Map.of("p", minimalEntry("text")));
        // only the fixed table rows should appear, no extra prose
        assertThat(result).doesNotContainPattern("(?m)^[A-Z].*\\.$");
    }

    @Test
    void generate_includesTypeRow() {
        var result = generator.generate("Title", "f.yaml", Map.of("p", minimalEntry("integer")));
        assertThat(result).contains("| **Type** | `integer` |");
    }

    @Test
    void generate_includesRequiredRowWhenTrue() {
        var entry = new ConfigDocEntry(null, "text", true, null, null, null, null, null);
        var result = generator.generate("Title", "f.yaml", Map.of("p", entry));
        assertThat(result).contains("| **Required** | yes |");
    }

    @Test
    void generate_skipsRequiredRowWhenFalse() {
        var result = generator.generate("Title", "f.yaml", Map.of("p", minimalEntry("text")));
        assertThat(result).doesNotContain("**Required**");
    }

    @Test
    void generate_includesDefaultValueRow() {
        var entry = new ConfigDocEntry(null, "integer", false, 5, null, null, null, null);
        var result = generator.generate("Title", "f.yaml", Map.of("p", entry));
        assertThat(result).contains("| **Default** | `5` |");
    }

    @Test
    void generate_includesPatternConstraint() {
        var entry = new ConfigDocEntry(null, "text", false, null, "A\\d\\dB", null, null, null);
        var result = generator.generate("Title", "f.yaml", Map.of("p", entry));
        assertThat(result).contains("| **Pattern** | `A\\d\\dB` |");
    }

    @Test
    void generate_includesMinMaxConstraints() {
        var entry = new ConfigDocEntry(null, "integer", false, null, null, 2, 10, null);
        var result = generator.generate("Title", "f.yaml", Map.of("p", entry));
        assertThat(result)
            .contains("| **Min** | `2` |")
            .contains("| **Max** | `10` |");
    }

    @Test
    void generate_includesEnumValues() {
        var entry = new ConfigDocEntry(null, "enum", false, null, null, null, null, List.of("red", "yellow", "orange"));
        var result = generator.generate("Title", "f.yaml", Map.of("p", entry));
        assertThat(result).contains("| **Values** | `red`, `yellow`, `orange` |");
    }

    @Test
    void generate_rendersMultipleEntriesInOrder() {
        var entries = new LinkedHashMap<String, ConfigDocEntry>();
        entries.put("prop.one", minimalEntry("text"));
        entries.put("prop.two", minimalEntry("boolean"));
        var result = generator.generate("Title", "f.yaml", entries);
        assertThat(result.indexOf("### `prop.one`")).isLessThan(result.indexOf("### `prop.two`"));
    }

}