package org.myjtools.openbbt.docgen;

import org.junit.jupiter.api.Test;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

class StepDocMarkdownGeneratorTest {

    private final StepDocMarkdownGenerator generator = new StepDocMarkdownGenerator();

    private StepDocEntry minimalEntry() {
        return new StepDocEntry("A simple step.", Map.of(), List.of(), null, null);
    }

    @Test
    void generate_includesTitleAsH1() {
        var result = generator.generate("My Docs", "steps.yaml", Map.of());
        assertThat(result).startsWith("# My Docs\n");
    }

    @Test
    void generate_includesAutogeneratedNotice() {
        var result = generator.generate("Title", "steps.yaml", Map.of());
        assertThat(result).contains("> Autogenerated from `steps.yaml`. Do not edit manually.");
    }

    @Test
    void generate_includesStepIdAsH3() {
        var steps = Map.of("my.step.id", minimalEntry());
        var result = generator.generate("Title", "steps.yaml", steps);
        assertThat(result).contains("### `my.step.id`");
    }

    @Test
    void generate_includesDescription() {
        var steps = Map.of("my.step", new StepDocEntry("Does something useful.", Map.of(), List.of(), null, null));
        var result = generator.generate("Title", "f.yaml", steps);
        assertThat(result).contains("Does something useful.");
    }

    @Test
    void generate_includesExpressionsTable() {
        var expressions = Map.of("en", "I do something with {param:text}");
        var steps = Map.of("my.step", new StepDocEntry("Desc", expressions, List.of(), null, null));
        var result = generator.generate("Title", "f.yaml", steps);
        assertThat(result)
            .contains("| Language | Expression |")
            .contains("| English | `I do something with {param:text}` |");
    }

    @Test
    void generate_mapsEnToEnglishAndEsToEspanol() {
        var expressions = new LinkedHashMap<String, String>();
        expressions.put("en", "English expr");
        expressions.put("es", "Expresión española");
        var steps = Map.of("my.step", new StepDocEntry("Desc", expressions, List.of(), null, null));
        var result = generator.generate("Title", "f.yaml", steps);
        assertThat(result)
            .contains("| English |")
            .contains("| Español |");
    }

    @Test
    void generate_usesLanguageCodeAsLabelForUnknownLanguages() {
        var expressions = Map.of("fr", "Faire quelque chose");
        var steps = Map.of("my.step", new StepDocEntry("Desc", expressions, List.of(), null, null));
        var result = generator.generate("Title", "f.yaml", steps);
        assertThat(result).contains("| fr |");
    }

    @Test
    void generate_skipsExpressionsTableWhenEmpty() {
        var result = generator.generate("Title", "f.yaml", Map.of("s", minimalEntry()));
        assertThat(result).doesNotContain("| Language | Expression |");
    }

    @Test
    void generate_includesParametersTable() {
        var params = List.of(new ParameterDoc("endpoint", "text", "The target URL"));
        var steps = Map.of("my.step", new StepDocEntry("Desc", Map.of(), params, null, null));
        var result = generator.generate("Title", "f.yaml", steps);
        assertThat(result)
            .contains("#### Parameters")
            .contains("| Name | Type | Description |")
            .contains("| `endpoint` | text | The target URL |");
    }

    @Test
    void generate_skipsParametersSectionWhenEmpty() {
        var result = generator.generate("Title", "f.yaml", Map.of("s", minimalEntry()));
        assertThat(result).doesNotContain("#### Parameters");
    }

    @Test
    void generate_includesBodySection() {
        var additionalData = Map.of("document", "Request body as JSON");
        var steps = Map.of("my.step", new StepDocEntry("Desc", Map.of(), List.of(), additionalData, null));
        var result = generator.generate("Title", "f.yaml", steps);
        assertThat(result)
            .contains("#### Body / Document")
            .contains("Request body as JSON");
    }

    @Test
    void generate_skipsBodySectionWhenAdditionalDataIsNull() {
        var result = generator.generate("Title", "f.yaml", Map.of("s", minimalEntry()));
        assertThat(result).doesNotContain("#### Body / Document");
    }

    @Test
    void generate_includesExampleInGherkinBlock() {
        var steps = Map.of("my.step", new StepDocEntry("Desc", Map.of(), List.of(), null, "Given I do something"));
        var result = generator.generate("Title", "f.yaml", steps);
        assertThat(result)
            .contains("#### Example")
            .contains("```gherkin")
            .contains("Given I do something")
            .contains("```");
    }

    @Test
    void generate_skipsExampleSectionWhenNull() {
        var result = generator.generate("Title", "f.yaml", Map.of("s", minimalEntry()));
        assertThat(result).doesNotContain("#### Example");
    }

    @Test
    void generate_rendersMultipleStepsInOrder() {
        var steps = new LinkedHashMap<String, StepDocEntry>();
        steps.put("step.one", minimalEntry());
        steps.put("step.two", minimalEntry());
        var result = generator.generate("Title", "f.yaml", steps);
        assertThat(result.indexOf("### `step.one`")).isLessThan(result.indexOf("### `step.two`"));
    }

}