package org.myjtools.openbbt.docgen;

import java.util.Map;
import java.util.stream.Collectors;

class ConfigDocMarkdownGenerator {

    String generate(String title, String inputFileName, Map<String, ConfigDocEntry> entries) {
        var sb = new StringBuilder();
        sb.append("# ").append(title).append("\n\n");
        sb.append("> Autogenerated from `").append(inputFileName).append("`. Do not edit manually.\n\n");
        for (var entry : entries.entrySet()) {
            appendEntry(sb, entry.getKey(), entry.getValue());
        }
        return sb.toString();
    }

    private void appendEntry(StringBuilder sb, String key, ConfigDocEntry entry) {
        sb.append("### `").append(key).append("`\n\n");

        if (entry.description() != null && !entry.description().isBlank()) {
            sb.append(entry.description().stripTrailing()).append("\n\n");
        }

        sb.append("| | |\n");
        sb.append("|---|---|\n");
        sb.append("| **Type** | `").append(entry.type()).append("` |\n");

        if (entry.required()) {
            sb.append("| **Required** | yes |\n");
        }
        if (entry.defaultValue() != null) {
            sb.append("| **Default** | `").append(entry.defaultValue()).append("` |\n");
        }
        if (entry.constraintPattern() != null) {
            sb.append("| **Pattern** | `").append(entry.constraintPattern()).append("` |\n");
        }
        if (entry.constraintMin() != null) {
            sb.append("| **Min** | `").append(entry.constraintMin()).append("` |\n");
        }
        if (entry.constraintMax() != null) {
            sb.append("| **Max** | `").append(entry.constraintMax()).append("` |\n");
        }
        if (entry.constraintValues() != null && !entry.constraintValues().isEmpty()) {
            String values = entry.constraintValues().stream()
                .map(v -> "`" + v + "`")
                .collect(Collectors.joining(", "));
            sb.append("| **Values** | ").append(values).append(" |\n");
        }

        sb.append("\n");
    }
}