# encoding: UTF-8

# number positive assertions
assertion.number.equals== _
assertion.number.greater=> _
assertion.number.less=< _
assertion.number.greater.equals=>= _
assertion.number.less.equals=<= _

# string positive assertions
assertion.string.equals== _
assertion.string.equals.ignore.case== _ \(case-insensitive\)
assertion.string.equals.ignore.whitespace== _ \(blank-insensitive\)
assertion.string.starts.with=starts _
assertion.string.starts.with.ignore.case=starts _ \(case-insensitive\)
assertion.string.ends.with=ends _
assertion.string.ends.with.ignore.case=ends _ \(case-insensitive\)
assertion.string.contains=has _
assertion.string.contains.ignore.case=has _ \(case-insensitive\)

assertion.generic.null=is null
assertion.generic.empty=is empty
assertion.generic.null.empty=is null/empty

# negative assertions
assertion.number.not.equals=not = _
assertion.number.not.greater=not > _
assertion.number.not.less=not < _
assertion.number.not.greater.equals=not >= _
assertion.number.not.less.equals=not <= _

assertion.string.not.equals=not = _
assertion.string.not.equals.ignore.case=not = _ \(case-insensitive\)
assertion.string.not.equals.ignore.whitespace=not = _ \(blank-insensitive\)
assertion.string.not.starts.with=not starts _
assertion.string.not.starts.with.ignore.case=not starts _ \(case-insensitive\)
assertion.string.not.ends.with=not ends _
assertion.string.not.ends.with.ignore.case=not ends _ \(case-insensitive\)
assertion.string.not.contains=not has _
assertion.string.not.contains.ignore.case=not has _ \(case-insensitive\)

assertion.generic.not.null=not is null
assertion.generic.not.empty=not is empty
assertion.generic.not.null.empty=not is null/empty

# temporal positive assertions
assertion.temporal.equals== _
assertion.temporal.after=> _
assertion.temporal.before=< _
assertion.temporal.after.equals=>= _
assertion.temporal.before.equals=<= _

# temporal negative assertions
assertion.temporal.not.equals=not = _
assertion.temporal.not.after=not > _
assertion.temporal.not.before=not < _
assertion.temporal.not.after.equals=not >= _
assertion.temporal.not.before.equals=not <= _
